2023-03-29 00:51:52,046 [22] INFO  FantasyOfSango.SangoServer - New Client connected
2023-03-29 00:52:17,197 [11] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:17,ip:127.0.0.1:54594, Data: F3-02-07-00-01-08-73-01-25-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-28-43-6C-6F-6E-65-29-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-36-2E-38-30-38-39-39-30-35-2C-22-59-22-3A-36-2E-38-32-39-31-38-38-38-32-2C-22-5A-22-3A-31-33-31-2E-34-30-33-32-35-39-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-36-2E-38-30-38-39-39-30-35-2C-22-59-22-3A-36-2E-37-33-38-34-37-31-39-38-2C-22-5A-22-3A-31-33-31-2E-34-30-33-32-35-39-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-38-54-31-36-3A-35-32-3A-31-37-2E-31-33-33-30-31-37-36-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-29 00:52:51,886 [15] INFO  FantasyOfSango.SangoServer - The Client is DisConnect
2023-03-29 00:53:51,995 [10] INFO  FantasyOfSango.SangoServer - New Client connected
2023-03-29 00:54:06,206 [15] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:18,ip:127.0.0.1:52905, Data: F3-02-07-00-01-08-73-01-25-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-28-43-6C-6F-6E-65-29-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-36-2E-31-37-37-30-34-37-37-2C-22-59-22-3A-36-2E-34-34-30-35-36-36-35-34-2C-22-5A-22-3A-31-32-39-2E-32-30-34-30-35-36-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-34-2E-37-35-36-35-39-31-38-2C-22-59-22-3A-36-2E-34-34-35-39-33-31-39-31-2C-22-5A-22-3A-31-32-38-2E-37-33-33-30-33-32-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-38-54-31-36-3A-35-34-3A-30-36-2E-31-34-37-38-39-35-34-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-29 00:54:47,734 [12] INFO  FantasyOfSango.SangoServer - The Client is DisConnect
2023-03-29 01:00:48,720 [13] INFO  FantasyOfSango.SangoServer - New Client connected
2023-03-29 01:01:57,728 [15] INFO  FantasyOfSango.SangoServer - The Client is DisConnect
2023-03-29 01:02:29,883 [20] INFO  FantasyOfSango.SangoServer - New Client connected
2023-03-29 01:02:58,775 [13] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:20,ip:127.0.0.1:63502, Data: F3-02-07-00-01-08-73-01-24-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-28-43-6C-6F-6E-65-29-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-36-2E-34-39-31-39-35-38-36-2C-22-59-22-3A-37-2E-33-37-36-32-30-31-31-35-2C-22-5A-22-3A-31-33-33-2E-38-35-36-37-30-35-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-37-2E-37-36-30-35-37-30-35-2C-22-59-22-3A-37-2E-33-34-34-33-38-36-31-2C-22-5A-22-3A-31-33-34-2E-35-35-33-37-38-37-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-38-54-31-37-3A-30-32-3A-35-38-2E-37-31-35-36-31-36-36-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-29 01:03:07,607 [21] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:20,ip:127.0.0.1:63502, Data: F3-02-07-00-01-08-73-01-25-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-28-43-6C-6F-6E-65-29-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-38-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-36-2E-34-39-31-39-35-38-36-2C-22-59-22-3A-37-2E-33-37-36-32-30-31-31-35-2C-22-5A-22-3A-31-33-33-2E-38-35-36-37-30-35-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-37-2E-37-36-30-35-37-30-35-2C-22-59-22-3A-37-2E-33-34-34-33-39-30-33-39-2C-22-5A-22-3A-31-33-34-2E-35-35-33-37-38-37-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-38-54-31-37-3A-30-33-3A-30-37-2E-35-38-37-35-37-39-38-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-29 01:03:10,901 [15] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:20,ip:127.0.0.1:63502, Data: F3-02-07-00-01-08-73-01-26-7B-22-46-69-67-68-74-54-79-70-65-43-6F-64-65-22-3A-30-2C-22-41-74-74-61-63-6B-65-72-41-63-63-6F-75-6E-74-22-3A-22-61-22-2C-22-44-61-6D-61-67-65-72-41-63-63-6F-75-6E-74-22-3A-22-4D-6F-6E-73-74-65-72-5F-48-69-6C-69-28-43-6C-6F-6E-65-29-22-2C-22-53-6B-69-6C-6C-43-6F-64-65-22-3A-35-2C-22-45-6C-65-6D-65-6E-74-52-65-61-63-74-69-6F-6E-43-6F-64-65-22-3A-31-30-2C-22-41-74-74-61-63-6B-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-36-2E-34-39-31-39-35-38-36-2C-22-59-22-3A-37-2E-33-37-36-32-30-31-31-35-2C-22-5A-22-3A-31-33-33-2E-38-35-36-37-30-35-7D-2C-22-44-61-6D-61-67-65-72-50-6F-73-69-74-69-6F-6E-22-3A-7B-22-58-22-3A-2D-35-37-2E-37-36-30-35-37-30-35-2C-22-59-22-3A-37-2E-33-34-34-33-39-30-33-39-2C-22-5A-22-3A-31-33-34-2E-35-35-33-37-38-37-7D-2C-22-44-61-74-65-54-69-6D-65-22-3A-22-32-30-32-33-2D-30-33-2D-32-38-54-31-37-3A-30-33-3A-31-30-2E-38-38-32-32-33-38-33-5A-22-7D,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.System.OnlineAttackSystem.SetElementAttackDamage(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 76
   at FantasyOfSango.System.OnlineAttackSystem.GetAttackResult(AttackDamageCache attackDamageCache) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\System\OnlineAttackSystem.cs:line 31
   at FantasyOfSango.Handler.AttackDamageHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\AttackDamageHandler.cs:line 22
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-29 01:03:20,580 [23] INFO  FantasyOfSango.SangoServer - The Client is DisConnect
2023-03-29 01:43:17,739 [1] INFO  Photon.SocketServer.ApplicationBase - Application is stopping: AppId=SangoTest
2023-03-29 01:43:17,761 [16] ERROR Photon.SocketServer.ApplicationBase - System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
   at FantasyOfSango.Threads.SyncPlayerTransformThreads.Update() in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Threads\SyncPlayerTransformThreads.cs:line 27
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2023-03-29 01:43:17,888 [1] INFO  FantasyOfSango.SangoServer - Sango Server is Shut Down
2023-03-29 01:43:17,888 [1] INFO  Photon.SocketServer.ApplicationBase - Application stop: AppId=SangoTest
2023-03-29 12:40:49,814 [1] INFO  FantasyOfSango.SangoServer - Sango Server is Running
2023-03-29 12:40:49,827 [1] INFO  FantasyOfSango.SangoServer - Init all Component
2023-03-29 12:40:49,829 [1] INFO  Photon.SocketServer.ApplicationBase - Application start: AppId=SangoTest; AppPath=D:\FantasyOfSango\Server\TestServer\Photon_v4\FantasyOfSango_Photon\deploy\FantasyOfSango, Type=FantasyOfSango.SangoServer 
2023-03-29 12:40:54,821 [11] INFO  FantasyOfSango.SangoServer - New Client connected
2023-03-29 12:41:46,422 [15] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:0,ip:127.0.0.1:58442, Data: F3-02-08-00-02-0A-69-00-00-00-01-00-73-00-0B-54-65-73-74-41-63-63-6F-75-6E-74,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.Cache.OnlineAccountCache.SetOnlineAvaterIndex(String account, AvaterCode avater) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Cache\OnlineAccountCache.cs:line 167
   at FantasyOfSango.Handler.ChooseAvaterHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\ChooseAvaterHandler.cs:line 21
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-29 12:41:47,819 [10] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:0,ip:127.0.0.1:58442, Data: F3-02-08-00-02-0A-69-00-00-00-02-00-73-00-0B-54-65-73-74-41-63-63-6F-75-6E-74,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.Cache.OnlineAccountCache.SetOnlineAvaterIndex(String account, AvaterCode avater) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Cache\OnlineAccountCache.cs:line 167
   at FantasyOfSango.Handler.ChooseAvaterHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\ChooseAvaterHandler.cs:line 21
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-29 12:41:47,819 [10] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:0,ip:127.0.0.1:58442, Data: F3-02-08-00-02-0A-69-00-00-00-02-00-73-00-0B-54-65-73-74-41-63-63-6F-75-6E-74,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.Cache.OnlineAccountCache.SetOnlineAvaterIndex(String account, AvaterCode avater) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Cache\OnlineAccountCache.cs:line 167
   at FantasyOfSango.Handler.ChooseAvaterHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\ChooseAvaterHandler.cs:line 21
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-29 12:41:49,434 [10] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:0,ip:127.0.0.1:58442, Data: F3-02-08-00-02-0A-69-00-00-00-00-00-73-00-0B-54-65-73-74-41-63-63-6F-75-6E-74,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.Cache.OnlineAccountCache.SetOnlineAvaterIndex(String account, AvaterCode avater) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Cache\OnlineAccountCache.cs:line 167
   at FantasyOfSango.Handler.ChooseAvaterHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\ChooseAvaterHandler.cs:line 21
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-29 12:41:49,434 [10] ERROR Photon.SocketServer.PeerBase - exception during handling of data.Peer:T:ClientPeer,ConnId:0,ip:127.0.0.1:58442, Data: F3-02-08-00-02-0A-69-00-00-00-00-00-73-00-0B-54-65-73-74-41-63-63-6F-75-6E-74,
Exception:System.NullReferenceException: Object reference not set to an instance of an object.
   at FantasyOfSango.Cache.OnlineAccountCache.SetOnlineAvaterIndex(String account, AvaterCode avater) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Cache\OnlineAccountCache.cs:line 167
   at FantasyOfSango.Handler.ChooseAvaterHandler.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters, ClientPeer peer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Handler\ChooseAvaterHandler.cs:line 21
   at FantasyOfSango.ClientPeer.OnOperationRequest(OperationRequest operationRequest, SendParameters sendParameters) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 37
   at Photon.SocketServer.PeerBase.OnReceive(Byte[] data, SendParameters sendParameters)
   at Photon.SocketServer.PeerBase.OnReceiveInternal(Byte[] data, SendParameters sendParameters, Int32 rtt, Int32 rttVariance, Int32 numFailures)
2023-03-29 12:42:10,020 [10] INFO  FantasyOfSango.SangoServer - The Client is DisConnect
2023-03-29 12:42:10,021 [10] ERROR ExitGames.Threading.FailSafeBatchExecutor - System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at FantasyOfSango.Cache.OnlineAccountCache.RemoveOnlineAccount(ClientPeer clientPeer) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\Cache\OnlineAccountCache.cs:line 59
   at FantasyOfSango.ClientPeer.OnDisconnect(DisconnectReason reasonCode, String reasonDetail) in D:\FantasyOfSango\Server\TestServer\TestServerScript\FantasyOfSango\FantasyOfSango\ClientPeer.cs:line 26
   at Photon.SocketServer.PeerBase.OnApplicationDisconnect(DisconnectReason reasonCode, String reasonDetail, Int32 rtt, Int32 rttVariance, Int32 numFailures)
   at Photon.SocketServer.PeerBase.<>c__DisplayClass2.<Photon.SocketServer.IManagedPeer.Application_OnDisconnect>b__1()
   at ExitGames.Threading.FailSafeBatchExecutor.Execute(Action action)
